### PR TITLE
Home Person component

### PR DESCRIPTION
**Pull request by ClaraFelix**

### CODE REVIEW

**Review by dev-luizf — COMMENTED** [review]
Can you add the courses list? Matheus said that we will maint them as it is in figma

**Comment by ClaraFelix** [comment]
> Can you add the courses list? Matheus said that we will maint them as it is in figma

Right, Luiz! I added :)

**Review by dev-luizf — CHANGES_REQUESTED** [review]
I forgot to mention, but can you please remove the search input from the page? And then align these elements:

Captura de tela de 2024-03-11 10-53-29
Captura de tela de 2024-03-11 10-53-24

**Comment by ClaraFelix** [comment]
> I forgot to mention, but can you please remove the search input from the page? And then align these elements:
> 
> Captura de tela de 2024-03-11 10-53-29 Captura de tela de 2024-03-11 10-53-24

Right, Luiz! I will make these adjustments now :)

**Review by dev-luizf — APPROVED** [review]

**Pull request merged**
